"""empty message

Revision ID: 19728359b101
Revises: 68676dcadcb2

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19728359b101'
down_revision = '68676dcadcb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_detected_device_mac_addr', table_name='detected_device')
    op.drop_table('detected_device')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detected_device',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('mac_addr', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('last_ip', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('vendor', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('uq_detected_device_mac_addr', 'detected_device', ['mac_addr'], unique=True)
    # ### end Alembic commands ###
